// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/loomnetwork/zombie_battleground/types/zb/zb.proto

/*
Package zb is a generated protocol buffer package.

It is generated from these files:
	github.com/loomnetwork/zombie_battleground/types/zb/zb.proto

It has these top-level messages:
	Account
	Deck
	Card
	CardViewInfo
	Coordinates
	Effect
	Ability
	CardList
	CardCollection
	CardSet
	CardLibrary
	Hero
	HeroInfo
	HeroInfoList
	GetHeroInfoListRequest
	GetHeroInfoListResponse
	AddExperienceRequest
	AddExperienceResponse
	GetHeroInfoRequest
	GetHeroAbilitiesRequest
	GetHeroAbilitiesResponse
	Skill
	HeroList
	CardCollectionList
	DeckList
	InitRequest
	UpsertAccountRequest
	GetAccountRequest
	GetDeckRequest
	GetDeckResponse
	CreateDeckRequest
	DeleteDeckRequest
	EditDeckRequest
	DecksResponse
	ListDecksRequest
	ListDecksResponse
	ListCardLibraryRequest
	ListCardLibraryResponse
	ListHeroRequest
	ListHeroResponse
	GetCollectionRequest
	GetCollectionResponse
*/
package zb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Account struct {
	UserId              string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PhoneNumberVerified bool   `protobuf:"varint,2,opt,name=phone_number_verified,json=phoneNumberVerified,proto3" json:"phone_number_verified,omitempty"`
	RewardRedeemed      bool   `protobuf:"varint,3,opt,name=reward_redeemed,json=rewardRedeemed,proto3" json:"reward_redeemed,omitempty"`
	IsKickstarter       bool   `protobuf:"varint,4,opt,name=is_kickstarter,json=isKickstarter,proto3" json:"is_kickstarter,omitempty"`
	Image               string `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	EmailNotification   bool   `protobuf:"varint,6,opt,name=email_notification,json=emailNotification,proto3" json:"email_notification,omitempty"`
	EloScore            int64  `protobuf:"varint,7,opt,name=elo_score,json=eloScore,proto3" json:"elo_score,omitempty"`
	CurrentTier         int32  `protobuf:"varint,8,opt,name=current_tier,json=currentTier,proto3" json:"current_tier,omitempty"`
	GameMembershipTier  int32  `protobuf:"varint,9,opt,name=game_membership_tier,json=gameMembershipTier,proto3" json:"game_membership_tier,omitempty"`
	Owner               []byte `protobuf:"bytes,10,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{0} }

func (m *Account) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Account) GetPhoneNumberVerified() bool {
	if m != nil {
		return m.PhoneNumberVerified
	}
	return false
}

func (m *Account) GetRewardRedeemed() bool {
	if m != nil {
		return m.RewardRedeemed
	}
	return false
}

func (m *Account) GetIsKickstarter() bool {
	if m != nil {
		return m.IsKickstarter
	}
	return false
}

func (m *Account) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Account) GetEmailNotification() bool {
	if m != nil {
		return m.EmailNotification
	}
	return false
}

func (m *Account) GetEloScore() int64 {
	if m != nil {
		return m.EloScore
	}
	return 0
}

func (m *Account) GetCurrentTier() int32 {
	if m != nil {
		return m.CurrentTier
	}
	return 0
}

func (m *Account) GetGameMembershipTier() int32 {
	if m != nil {
		return m.GameMembershipTier
	}
	return 0
}

func (m *Account) GetOwner() []byte {
	if m != nil {
		return m.Owner
	}
	return nil
}

type Deck struct {
	Name   string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	HeroId int64             `protobuf:"varint,2,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"`
	Cards  []*CardCollection `protobuf:"bytes,3,rep,name=cards" json:"cards,omitempty"`
}

func (m *Deck) Reset()                    { *m = Deck{} }
func (m *Deck) String() string            { return proto.CompactTextString(m) }
func (*Deck) ProtoMessage()               {}
func (*Deck) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{1} }

func (m *Deck) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Deck) GetHeroId() int64 {
	if m != nil {
		return m.HeroId
	}
	return 0
}

func (m *Deck) GetCards() []*CardCollection {
	if m != nil {
		return m.Cards
	}
	return nil
}

type Card struct {
	Id           int64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind         string        `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Element      string        `protobuf:"bytes,3,opt,name=element,proto3" json:"element,omitempty"`
	Name         string        `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description  string        `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	FlavorText   string        `protobuf:"bytes,6,opt,name=flavorText,proto3" json:"flavorText,omitempty"`
	Picture      string        `protobuf:"bytes,7,opt,name=picture,proto3" json:"picture,omitempty"`
	Rank         string        `protobuf:"bytes,8,opt,name=rank,proto3" json:"rank,omitempty"`
	Type         string        `protobuf:"bytes,9,opt,name=type,proto3" json:"type,omitempty"`
	Rarity       string        `protobuf:"bytes,10,opt,name=rarity,proto3" json:"rarity,omitempty"`
	Damage       int32         `protobuf:"varint,11,opt,name=damage,proto3" json:"damage,omitempty"`
	Health       int32         `protobuf:"varint,12,opt,name=health,proto3" json:"health,omitempty"`
	Cost         int32         `protobuf:"varint,13,opt,name=cost,proto3" json:"cost,omitempty"`
	Ability      string        `protobuf:"bytes,14,opt,name=ability,proto3" json:"ability,omitempty"`
	CardViewInfo *CardViewInfo `protobuf:"bytes,15,opt,name=card_view_info,json=cardViewInfo" json:"card_view_info,omitempty"`
	Effects      []*Effect     `protobuf:"bytes,16,rep,name=effects" json:"effects,omitempty"`
	Abilities    []*Ability    `protobuf:"bytes,17,rep,name=abilities" json:"abilities,omitempty"`
}

func (m *Card) Reset()                    { *m = Card{} }
func (m *Card) String() string            { return proto.CompactTextString(m) }
func (*Card) ProtoMessage()               {}
func (*Card) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{2} }

func (m *Card) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Card) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Card) GetElement() string {
	if m != nil {
		return m.Element
	}
	return ""
}

func (m *Card) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Card) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Card) GetFlavorText() string {
	if m != nil {
		return m.FlavorText
	}
	return ""
}

func (m *Card) GetPicture() string {
	if m != nil {
		return m.Picture
	}
	return ""
}

func (m *Card) GetRank() string {
	if m != nil {
		return m.Rank
	}
	return ""
}

func (m *Card) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Card) GetRarity() string {
	if m != nil {
		return m.Rarity
	}
	return ""
}

func (m *Card) GetDamage() int32 {
	if m != nil {
		return m.Damage
	}
	return 0
}

func (m *Card) GetHealth() int32 {
	if m != nil {
		return m.Health
	}
	return 0
}

func (m *Card) GetCost() int32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *Card) GetAbility() string {
	if m != nil {
		return m.Ability
	}
	return ""
}

func (m *Card) GetCardViewInfo() *CardViewInfo {
	if m != nil {
		return m.CardViewInfo
	}
	return nil
}

func (m *Card) GetEffects() []*Effect {
	if m != nil {
		return m.Effects
	}
	return nil
}

func (m *Card) GetAbilities() []*Ability {
	if m != nil {
		return m.Abilities
	}
	return nil
}

type CardViewInfo struct {
	Position *Coordinates `protobuf:"bytes,1,opt,name=position" json:"position,omitempty"`
	Scale    *Coordinates `protobuf:"bytes,2,opt,name=scale" json:"scale,omitempty"`
}

func (m *CardViewInfo) Reset()                    { *m = CardViewInfo{} }
func (m *CardViewInfo) String() string            { return proto.CompactTextString(m) }
func (*CardViewInfo) ProtoMessage()               {}
func (*CardViewInfo) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{3} }

func (m *CardViewInfo) GetPosition() *Coordinates {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *CardViewInfo) GetScale() *Coordinates {
	if m != nil {
		return m.Scale
	}
	return nil
}

type Coordinates struct {
	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
}

func (m *Coordinates) Reset()                    { *m = Coordinates{} }
func (m *Coordinates) String() string            { return proto.CompactTextString(m) }
func (*Coordinates) ProtoMessage()               {}
func (*Coordinates) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{4} }

func (m *Coordinates) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Coordinates) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Coordinates) GetZ() float32 {
	if m != nil {
		return m.Z
	}
	return 0
}

type Effect struct {
	Trigger  string `protobuf:"bytes,1,opt,name=trigger,proto3" json:"trigger,omitempty"`
	Effect   string `protobuf:"bytes,2,opt,name=effect,proto3" json:"effect,omitempty"`
	Duration string `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Target   string `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	Limit    string `protobuf:"bytes,5,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (m *Effect) Reset()                    { *m = Effect{} }
func (m *Effect) String() string            { return proto.CompactTextString(m) }
func (*Effect) ProtoMessage()               {}
func (*Effect) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{5} }

func (m *Effect) GetTrigger() string {
	if m != nil {
		return m.Trigger
	}
	return ""
}

func (m *Effect) GetEffect() string {
	if m != nil {
		return m.Effect
	}
	return ""
}

func (m *Effect) GetDuration() string {
	if m != nil {
		return m.Duration
	}
	return ""
}

func (m *Effect) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *Effect) GetLimit() string {
	if m != nil {
		return m.Limit
	}
	return ""
}

type Ability struct {
	Type         string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	ActivityType string `protobuf:"bytes,2,opt,name=activity_type,json=activityType,proto3" json:"activity_type,omitempty"`
	CallType     string `protobuf:"bytes,3,opt,name=call_type,json=callType,proto3" json:"call_type,omitempty"`
	TargetType   string `protobuf:"bytes,4,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	Value        int32  `protobuf:"varint,5,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Ability) Reset()                    { *m = Ability{} }
func (m *Ability) String() string            { return proto.CompactTextString(m) }
func (*Ability) ProtoMessage()               {}
func (*Ability) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{6} }

func (m *Ability) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Ability) GetActivityType() string {
	if m != nil {
		return m.ActivityType
	}
	return ""
}

func (m *Ability) GetCallType() string {
	if m != nil {
		return m.CallType
	}
	return ""
}

func (m *Ability) GetTargetType() string {
	if m != nil {
		return m.TargetType
	}
	return ""
}

func (m *Ability) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type CardList struct {
	Cards []*Card `protobuf:"bytes,1,rep,name=cards" json:"cards,omitempty"`
}

func (m *CardList) Reset()                    { *m = CardList{} }
func (m *CardList) String() string            { return proto.CompactTextString(m) }
func (*CardList) ProtoMessage()               {}
func (*CardList) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{7} }

func (m *CardList) GetCards() []*Card {
	if m != nil {
		return m.Cards
	}
	return nil
}

type CardCollection struct {
	CardName string `protobuf:"bytes,1,opt,name=card_name,json=cardName,proto3" json:"card_name,omitempty"`
	Amount   int64  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *CardCollection) Reset()                    { *m = CardCollection{} }
func (m *CardCollection) String() string            { return proto.CompactTextString(m) }
func (*CardCollection) ProtoMessage()               {}
func (*CardCollection) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{8} }

func (m *CardCollection) GetCardName() string {
	if m != nil {
		return m.CardName
	}
	return ""
}

func (m *CardCollection) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type CardSet struct {
	Name  string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cards []*Card `protobuf:"bytes,2,rep,name=cards" json:"cards,omitempty"`
}

func (m *CardSet) Reset()                    { *m = CardSet{} }
func (m *CardSet) String() string            { return proto.CompactTextString(m) }
func (*CardSet) ProtoMessage()               {}
func (*CardSet) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{9} }

func (m *CardSet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CardSet) GetCards() []*Card {
	if m != nil {
		return m.Cards
	}
	return nil
}

type CardLibrary struct {
	Sets []*CardSet `protobuf:"bytes,1,rep,name=sets" json:"sets,omitempty"`
}

func (m *CardLibrary) Reset()                    { *m = CardLibrary{} }
func (m *CardLibrary) String() string            { return proto.CompactTextString(m) }
func (*CardLibrary) ProtoMessage()               {}
func (*CardLibrary) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{10} }

func (m *CardLibrary) GetSets() []*CardSet {
	if m != nil {
		return m.Sets
	}
	return nil
}

type Hero struct {
	HeroId  int64    `protobuf:"varint,1,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"`
	Icon    string   `protobuf:"bytes,2,opt,name=icon,proto3" json:"icon,omitempty"`
	Name    string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Element int32    `protobuf:"varint,4,opt,name=element,proto3" json:"element,omitempty"`
	Skills  []*Skill `protobuf:"bytes,5,rep,name=skills" json:"skills,omitempty"`
}

func (m *Hero) Reset()                    { *m = Hero{} }
func (m *Hero) String() string            { return proto.CompactTextString(m) }
func (*Hero) ProtoMessage()               {}
func (*Hero) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{11} }

func (m *Hero) GetHeroId() int64 {
	if m != nil {
		return m.HeroId
	}
	return 0
}

func (m *Hero) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *Hero) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Hero) GetElement() int32 {
	if m != nil {
		return m.Element
	}
	return 0
}

func (m *Hero) GetSkills() []*Skill {
	if m != nil {
		return m.Skills
	}
	return nil
}

type HeroInfo struct {
	HeroId     int64      `protobuf:"varint,1,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"`
	Experience int64      `protobuf:"varint,2,opt,name=experience,proto3" json:"experience,omitempty"`
	Abilities  []*Ability `protobuf:"bytes,3,rep,name=abilities" json:"abilities,omitempty"`
}

func (m *HeroInfo) Reset()                    { *m = HeroInfo{} }
func (m *HeroInfo) String() string            { return proto.CompactTextString(m) }
func (*HeroInfo) ProtoMessage()               {}
func (*HeroInfo) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{12} }

func (m *HeroInfo) GetHeroId() int64 {
	if m != nil {
		return m.HeroId
	}
	return 0
}

func (m *HeroInfo) GetExperience() int64 {
	if m != nil {
		return m.Experience
	}
	return 0
}

func (m *HeroInfo) GetAbilities() []*Ability {
	if m != nil {
		return m.Abilities
	}
	return nil
}

type HeroInfoList struct {
	Heroes []*HeroInfo `protobuf:"bytes,1,rep,name=heroes" json:"heroes,omitempty"`
}

func (m *HeroInfoList) Reset()                    { *m = HeroInfoList{} }
func (m *HeroInfoList) String() string            { return proto.CompactTextString(m) }
func (*HeroInfoList) ProtoMessage()               {}
func (*HeroInfoList) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{13} }

func (m *HeroInfoList) GetHeroes() []*HeroInfo {
	if m != nil {
		return m.Heroes
	}
	return nil
}

type GetHeroInfoListRequest struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (m *GetHeroInfoListRequest) Reset()                    { *m = GetHeroInfoListRequest{} }
func (m *GetHeroInfoListRequest) String() string            { return proto.CompactTextString(m) }
func (*GetHeroInfoListRequest) ProtoMessage()               {}
func (*GetHeroInfoListRequest) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{14} }

func (m *GetHeroInfoListRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetHeroInfoListResponse struct {
	Heroes []*HeroInfo `protobuf:"bytes,1,rep,name=heroes" json:"heroes,omitempty"`
}

func (m *GetHeroInfoListResponse) Reset()                    { *m = GetHeroInfoListResponse{} }
func (m *GetHeroInfoListResponse) String() string            { return proto.CompactTextString(m) }
func (*GetHeroInfoListResponse) ProtoMessage()               {}
func (*GetHeroInfoListResponse) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{15} }

func (m *GetHeroInfoListResponse) GetHeroes() []*HeroInfo {
	if m != nil {
		return m.Heroes
	}
	return nil
}

type AddExperienceRequest struct {
	UserId     string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	HeroId     int64  `protobuf:"varint,2,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"`
	Experience int64  `protobuf:"varint,3,opt,name=experience,proto3" json:"experience,omitempty"`
}

func (m *AddExperienceRequest) Reset()                    { *m = AddExperienceRequest{} }
func (m *AddExperienceRequest) String() string            { return proto.CompactTextString(m) }
func (*AddExperienceRequest) ProtoMessage()               {}
func (*AddExperienceRequest) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{16} }

func (m *AddExperienceRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AddExperienceRequest) GetHeroId() int64 {
	if m != nil {
		return m.HeroId
	}
	return 0
}

func (m *AddExperienceRequest) GetExperience() int64 {
	if m != nil {
		return m.Experience
	}
	return 0
}

type AddExperienceResponse struct {
	HeroId     int64 `protobuf:"varint,1,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"`
	Experience int64 `protobuf:"varint,2,opt,name=experience,proto3" json:"experience,omitempty"`
}

func (m *AddExperienceResponse) Reset()                    { *m = AddExperienceResponse{} }
func (m *AddExperienceResponse) String() string            { return proto.CompactTextString(m) }
func (*AddExperienceResponse) ProtoMessage()               {}
func (*AddExperienceResponse) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{17} }

func (m *AddExperienceResponse) GetHeroId() int64 {
	if m != nil {
		return m.HeroId
	}
	return 0
}

func (m *AddExperienceResponse) GetExperience() int64 {
	if m != nil {
		return m.Experience
	}
	return 0
}

type GetHeroInfoRequest struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	HeroId int64  `protobuf:"varint,2,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"`
}

func (m *GetHeroInfoRequest) Reset()                    { *m = GetHeroInfoRequest{} }
func (m *GetHeroInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*GetHeroInfoRequest) ProtoMessage()               {}
func (*GetHeroInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{18} }

func (m *GetHeroInfoRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetHeroInfoRequest) GetHeroId() int64 {
	if m != nil {
		return m.HeroId
	}
	return 0
}

type GetHeroAbilitiesRequest struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	HeroId int64  `protobuf:"varint,2,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"`
}

func (m *GetHeroAbilitiesRequest) Reset()                    { *m = GetHeroAbilitiesRequest{} }
func (m *GetHeroAbilitiesRequest) String() string            { return proto.CompactTextString(m) }
func (*GetHeroAbilitiesRequest) ProtoMessage()               {}
func (*GetHeroAbilitiesRequest) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{19} }

func (m *GetHeroAbilitiesRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetHeroAbilitiesRequest) GetHeroId() int64 {
	if m != nil {
		return m.HeroId
	}
	return 0
}

type GetHeroAbilitiesResponse struct {
	Abilities []*Ability `protobuf:"bytes,1,rep,name=abilities" json:"abilities,omitempty"`
}

func (m *GetHeroAbilitiesResponse) Reset()                    { *m = GetHeroAbilitiesResponse{} }
func (m *GetHeroAbilitiesResponse) String() string            { return proto.CompactTextString(m) }
func (*GetHeroAbilitiesResponse) ProtoMessage()               {}
func (*GetHeroAbilitiesResponse) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{20} }

func (m *GetHeroAbilitiesResponse) GetAbilities() []*Ability {
	if m != nil {
		return m.Abilities
	}
	return nil
}

type Skill struct {
	Title           string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	SkillType       int32  `protobuf:"varint,2,opt,name=skillType,proto3" json:"skillType,omitempty"`
	SkillTargetType int32  `protobuf:"varint,3,opt,name=skillTargetType,proto3" json:"skillTargetType,omitempty"`
	Cost            int32  `protobuf:"varint,4,opt,name=cost,proto3" json:"cost,omitempty"`
	Value           int32  `protobuf:"varint,5,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Skill) Reset()                    { *m = Skill{} }
func (m *Skill) String() string            { return proto.CompactTextString(m) }
func (*Skill) ProtoMessage()               {}
func (*Skill) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{21} }

func (m *Skill) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Skill) GetSkillType() int32 {
	if m != nil {
		return m.SkillType
	}
	return 0
}

func (m *Skill) GetSkillTargetType() int32 {
	if m != nil {
		return m.SkillTargetType
	}
	return 0
}

func (m *Skill) GetCost() int32 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *Skill) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type HeroList struct {
	Heroes []*Hero `protobuf:"bytes,1,rep,name=heroes" json:"heroes,omitempty"`
}

func (m *HeroList) Reset()                    { *m = HeroList{} }
func (m *HeroList) String() string            { return proto.CompactTextString(m) }
func (*HeroList) ProtoMessage()               {}
func (*HeroList) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{22} }

func (m *HeroList) GetHeroes() []*Hero {
	if m != nil {
		return m.Heroes
	}
	return nil
}

type CardCollectionList struct {
	Cards []*CardCollection `protobuf:"bytes,1,rep,name=cards" json:"cards,omitempty"`
}

func (m *CardCollectionList) Reset()                    { *m = CardCollectionList{} }
func (m *CardCollectionList) String() string            { return proto.CompactTextString(m) }
func (*CardCollectionList) ProtoMessage()               {}
func (*CardCollectionList) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{23} }

func (m *CardCollectionList) GetCards() []*CardCollection {
	if m != nil {
		return m.Cards
	}
	return nil
}

type DeckList struct {
	Decks []*Deck `protobuf:"bytes,1,rep,name=decks" json:"decks,omitempty"`
}

func (m *DeckList) Reset()                    { *m = DeckList{} }
func (m *DeckList) String() string            { return proto.CompactTextString(m) }
func (*DeckList) ProtoMessage()               {}
func (*DeckList) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{24} }

func (m *DeckList) GetDecks() []*Deck {
	if m != nil {
		return m.Decks
	}
	return nil
}

type InitRequest struct {
	DefaultDecks      []*Deck           `protobuf:"bytes,1,rep,name=default_decks,json=defaultDecks" json:"default_decks,omitempty"`
	DefaultCollection []*CardCollection `protobuf:"bytes,2,rep,name=default_collection,json=defaultCollection" json:"default_collection,omitempty"`
	DefaultHeroes     []*HeroInfo       `protobuf:"bytes,3,rep,name=default_heroes,json=defaultHeroes" json:"default_heroes,omitempty"`
	Cards             []*Card           `protobuf:"bytes,4,rep,name=cards" json:"cards,omitempty"`
	Heroes            []*Hero           `protobuf:"bytes,5,rep,name=heroes" json:"heroes,omitempty"`
}

func (m *InitRequest) Reset()                    { *m = InitRequest{} }
func (m *InitRequest) String() string            { return proto.CompactTextString(m) }
func (*InitRequest) ProtoMessage()               {}
func (*InitRequest) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{25} }

func (m *InitRequest) GetDefaultDecks() []*Deck {
	if m != nil {
		return m.DefaultDecks
	}
	return nil
}

func (m *InitRequest) GetDefaultCollection() []*CardCollection {
	if m != nil {
		return m.DefaultCollection
	}
	return nil
}

func (m *InitRequest) GetDefaultHeroes() []*HeroInfo {
	if m != nil {
		return m.DefaultHeroes
	}
	return nil
}

func (m *InitRequest) GetCards() []*Card {
	if m != nil {
		return m.Cards
	}
	return nil
}

func (m *InitRequest) GetHeroes() []*Hero {
	if m != nil {
		return m.Heroes
	}
	return nil
}

type UpsertAccountRequest struct {
	UserId              string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PhoneNumberVerified bool   `protobuf:"varint,2,opt,name=phone_number_verified,json=phoneNumberVerified,proto3" json:"phone_number_verified,omitempty"`
	RewardRedeemed      bool   `protobuf:"varint,3,opt,name=reward_redeemed,json=rewardRedeemed,proto3" json:"reward_redeemed,omitempty"`
	IsKickstarter       bool   `protobuf:"varint,4,opt,name=is_kickstarter,json=isKickstarter,proto3" json:"is_kickstarter,omitempty"`
	Image               string `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	EmailNotification   bool   `protobuf:"varint,6,opt,name=email_notification,json=emailNotification,proto3" json:"email_notification,omitempty"`
	EloScore            int64  `protobuf:"varint,7,opt,name=elo_score,json=eloScore,proto3" json:"elo_score,omitempty"`
	CurrentTier         int32  `protobuf:"varint,8,opt,name=current_tier,json=currentTier,proto3" json:"current_tier,omitempty"`
	GameMembershipTier  int32  `protobuf:"varint,9,opt,name=game_membership_tier,json=gameMembershipTier,proto3" json:"game_membership_tier,omitempty"`
}

func (m *UpsertAccountRequest) Reset()                    { *m = UpsertAccountRequest{} }
func (m *UpsertAccountRequest) String() string            { return proto.CompactTextString(m) }
func (*UpsertAccountRequest) ProtoMessage()               {}
func (*UpsertAccountRequest) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{26} }

func (m *UpsertAccountRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpsertAccountRequest) GetPhoneNumberVerified() bool {
	if m != nil {
		return m.PhoneNumberVerified
	}
	return false
}

func (m *UpsertAccountRequest) GetRewardRedeemed() bool {
	if m != nil {
		return m.RewardRedeemed
	}
	return false
}

func (m *UpsertAccountRequest) GetIsKickstarter() bool {
	if m != nil {
		return m.IsKickstarter
	}
	return false
}

func (m *UpsertAccountRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *UpsertAccountRequest) GetEmailNotification() bool {
	if m != nil {
		return m.EmailNotification
	}
	return false
}

func (m *UpsertAccountRequest) GetEloScore() int64 {
	if m != nil {
		return m.EloScore
	}
	return 0
}

func (m *UpsertAccountRequest) GetCurrentTier() int32 {
	if m != nil {
		return m.CurrentTier
	}
	return 0
}

func (m *UpsertAccountRequest) GetGameMembershipTier() int32 {
	if m != nil {
		return m.GameMembershipTier
	}
	return 0
}

type GetAccountRequest struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (m *GetAccountRequest) Reset()                    { *m = GetAccountRequest{} }
func (m *GetAccountRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAccountRequest) ProtoMessage()               {}
func (*GetAccountRequest) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{27} }

func (m *GetAccountRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetDeckRequest struct {
	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeckName string `protobuf:"bytes,2,opt,name=deck_name,json=deckName,proto3" json:"deck_name,omitempty"`
}

func (m *GetDeckRequest) Reset()                    { *m = GetDeckRequest{} }
func (m *GetDeckRequest) String() string            { return proto.CompactTextString(m) }
func (*GetDeckRequest) ProtoMessage()               {}
func (*GetDeckRequest) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{28} }

func (m *GetDeckRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetDeckRequest) GetDeckName() string {
	if m != nil {
		return m.DeckName
	}
	return ""
}

type GetDeckResponse struct {
	Deck *Deck `protobuf:"bytes,2,opt,name=deck" json:"deck,omitempty"`
}

func (m *GetDeckResponse) Reset()                    { *m = GetDeckResponse{} }
func (m *GetDeckResponse) String() string            { return proto.CompactTextString(m) }
func (*GetDeckResponse) ProtoMessage()               {}
func (*GetDeckResponse) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{29} }

func (m *GetDeckResponse) GetDeck() *Deck {
	if m != nil {
		return m.Deck
	}
	return nil
}

type CreateDeckRequest struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Deck   *Deck  `protobuf:"bytes,2,opt,name=deck" json:"deck,omitempty"`
}

func (m *CreateDeckRequest) Reset()                    { *m = CreateDeckRequest{} }
func (m *CreateDeckRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateDeckRequest) ProtoMessage()               {}
func (*CreateDeckRequest) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{30} }

func (m *CreateDeckRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *CreateDeckRequest) GetDeck() *Deck {
	if m != nil {
		return m.Deck
	}
	return nil
}

type DeleteDeckRequest struct {
	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeckName string `protobuf:"bytes,2,opt,name=deck_name,json=deckName,proto3" json:"deck_name,omitempty"`
}

func (m *DeleteDeckRequest) Reset()                    { *m = DeleteDeckRequest{} }
func (m *DeleteDeckRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteDeckRequest) ProtoMessage()               {}
func (*DeleteDeckRequest) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{31} }

func (m *DeleteDeckRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *DeleteDeckRequest) GetDeckName() string {
	if m != nil {
		return m.DeckName
	}
	return ""
}

type EditDeckRequest struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Deck   *Deck  `protobuf:"bytes,2,opt,name=deck" json:"deck,omitempty"`
}

func (m *EditDeckRequest) Reset()                    { *m = EditDeckRequest{} }
func (m *EditDeckRequest) String() string            { return proto.CompactTextString(m) }
func (*EditDeckRequest) ProtoMessage()               {}
func (*EditDeckRequest) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{32} }

func (m *EditDeckRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *EditDeckRequest) GetDeck() *Deck {
	if m != nil {
		return m.Deck
	}
	return nil
}

type DecksResponse struct {
	UserId string  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Decks  []*Deck `protobuf:"bytes,2,rep,name=decks" json:"decks,omitempty"`
}

func (m *DecksResponse) Reset()                    { *m = DecksResponse{} }
func (m *DecksResponse) String() string            { return proto.CompactTextString(m) }
func (*DecksResponse) ProtoMessage()               {}
func (*DecksResponse) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{33} }

func (m *DecksResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *DecksResponse) GetDecks() []*Deck {
	if m != nil {
		return m.Decks
	}
	return nil
}

type ListDecksRequest struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (m *ListDecksRequest) Reset()                    { *m = ListDecksRequest{} }
func (m *ListDecksRequest) String() string            { return proto.CompactTextString(m) }
func (*ListDecksRequest) ProtoMessage()               {}
func (*ListDecksRequest) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{34} }

func (m *ListDecksRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ListDecksResponse struct {
	Decks []*Deck `protobuf:"bytes,1,rep,name=decks" json:"decks,omitempty"`
}

func (m *ListDecksResponse) Reset()                    { *m = ListDecksResponse{} }
func (m *ListDecksResponse) String() string            { return proto.CompactTextString(m) }
func (*ListDecksResponse) ProtoMessage()               {}
func (*ListDecksResponse) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{35} }

func (m *ListDecksResponse) GetDecks() []*Deck {
	if m != nil {
		return m.Decks
	}
	return nil
}

type ListCardLibraryRequest struct {
}

func (m *ListCardLibraryRequest) Reset()                    { *m = ListCardLibraryRequest{} }
func (m *ListCardLibraryRequest) String() string            { return proto.CompactTextString(m) }
func (*ListCardLibraryRequest) ProtoMessage()               {}
func (*ListCardLibraryRequest) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{36} }

type ListCardLibraryResponse struct {
	Sets []*CardSet `protobuf:"bytes,1,rep,name=sets" json:"sets,omitempty"`
}

func (m *ListCardLibraryResponse) Reset()                    { *m = ListCardLibraryResponse{} }
func (m *ListCardLibraryResponse) String() string            { return proto.CompactTextString(m) }
func (*ListCardLibraryResponse) ProtoMessage()               {}
func (*ListCardLibraryResponse) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{37} }

func (m *ListCardLibraryResponse) GetSets() []*CardSet {
	if m != nil {
		return m.Sets
	}
	return nil
}

type ListHeroRequest struct {
}

func (m *ListHeroRequest) Reset()                    { *m = ListHeroRequest{} }
func (m *ListHeroRequest) String() string            { return proto.CompactTextString(m) }
func (*ListHeroRequest) ProtoMessage()               {}
func (*ListHeroRequest) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{38} }

type ListHeroResponse struct {
	Heroes []*Hero `protobuf:"bytes,1,rep,name=heroes" json:"heroes,omitempty"`
}

func (m *ListHeroResponse) Reset()                    { *m = ListHeroResponse{} }
func (m *ListHeroResponse) String() string            { return proto.CompactTextString(m) }
func (*ListHeroResponse) ProtoMessage()               {}
func (*ListHeroResponse) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{39} }

func (m *ListHeroResponse) GetHeroes() []*Hero {
	if m != nil {
		return m.Heroes
	}
	return nil
}

type GetCollectionRequest struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (m *GetCollectionRequest) Reset()                    { *m = GetCollectionRequest{} }
func (m *GetCollectionRequest) String() string            { return proto.CompactTextString(m) }
func (*GetCollectionRequest) ProtoMessage()               {}
func (*GetCollectionRequest) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{40} }

func (m *GetCollectionRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetCollectionResponse struct {
	Cards []*CardCollection `protobuf:"bytes,1,rep,name=cards" json:"cards,omitempty"`
}

func (m *GetCollectionResponse) Reset()                    { *m = GetCollectionResponse{} }
func (m *GetCollectionResponse) String() string            { return proto.CompactTextString(m) }
func (*GetCollectionResponse) ProtoMessage()               {}
func (*GetCollectionResponse) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{41} }

func (m *GetCollectionResponse) GetCards() []*CardCollection {
	if m != nil {
		return m.Cards
	}
	return nil
}

func init() {
	proto.RegisterType((*Account)(nil), "Account")
	proto.RegisterType((*Deck)(nil), "Deck")
	proto.RegisterType((*Card)(nil), "Card")
	proto.RegisterType((*CardViewInfo)(nil), "CardViewInfo")
	proto.RegisterType((*Coordinates)(nil), "Coordinates")
	proto.RegisterType((*Effect)(nil), "Effect")
	proto.RegisterType((*Ability)(nil), "Ability")
	proto.RegisterType((*CardList)(nil), "CardList")
	proto.RegisterType((*CardCollection)(nil), "CardCollection")
	proto.RegisterType((*CardSet)(nil), "CardSet")
	proto.RegisterType((*CardLibrary)(nil), "CardLibrary")
	proto.RegisterType((*Hero)(nil), "Hero")
	proto.RegisterType((*HeroInfo)(nil), "HeroInfo")
	proto.RegisterType((*HeroInfoList)(nil), "HeroInfoList")
	proto.RegisterType((*GetHeroInfoListRequest)(nil), "GetHeroInfoListRequest")
	proto.RegisterType((*GetHeroInfoListResponse)(nil), "GetHeroInfoListResponse")
	proto.RegisterType((*AddExperienceRequest)(nil), "AddExperienceRequest")
	proto.RegisterType((*AddExperienceResponse)(nil), "AddExperienceResponse")
	proto.RegisterType((*GetHeroInfoRequest)(nil), "GetHeroInfoRequest")
	proto.RegisterType((*GetHeroAbilitiesRequest)(nil), "GetHeroAbilitiesRequest")
	proto.RegisterType((*GetHeroAbilitiesResponse)(nil), "GetHeroAbilitiesResponse")
	proto.RegisterType((*Skill)(nil), "Skill")
	proto.RegisterType((*HeroList)(nil), "HeroList")
	proto.RegisterType((*CardCollectionList)(nil), "CardCollectionList")
	proto.RegisterType((*DeckList)(nil), "DeckList")
	proto.RegisterType((*InitRequest)(nil), "InitRequest")
	proto.RegisterType((*UpsertAccountRequest)(nil), "UpsertAccountRequest")
	proto.RegisterType((*GetAccountRequest)(nil), "GetAccountRequest")
	proto.RegisterType((*GetDeckRequest)(nil), "GetDeckRequest")
	proto.RegisterType((*GetDeckResponse)(nil), "GetDeckResponse")
	proto.RegisterType((*CreateDeckRequest)(nil), "CreateDeckRequest")
	proto.RegisterType((*DeleteDeckRequest)(nil), "DeleteDeckRequest")
	proto.RegisterType((*EditDeckRequest)(nil), "EditDeckRequest")
	proto.RegisterType((*DecksResponse)(nil), "DecksResponse")
	proto.RegisterType((*ListDecksRequest)(nil), "ListDecksRequest")
	proto.RegisterType((*ListDecksResponse)(nil), "ListDecksResponse")
	proto.RegisterType((*ListCardLibraryRequest)(nil), "ListCardLibraryRequest")
	proto.RegisterType((*ListCardLibraryResponse)(nil), "ListCardLibraryResponse")
	proto.RegisterType((*ListHeroRequest)(nil), "ListHeroRequest")
	proto.RegisterType((*ListHeroResponse)(nil), "ListHeroResponse")
	proto.RegisterType((*GetCollectionRequest)(nil), "GetCollectionRequest")
	proto.RegisterType((*GetCollectionResponse)(nil), "GetCollectionResponse")
}

func init() {
	proto.RegisterFile("github.com/loomnetwork/zombie_battleground/types/zb/zb.proto", fileDescriptorZb)
}

var fileDescriptorZb = []byte{
	// 1470 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x58, 0x4b, 0x6f, 0x1b, 0x47,
	0x12, 0xc6, 0xf0, 0xcd, 0x22, 0x45, 0x9a, 0xbd, 0xb2, 0x3c, 0xbb, 0xf2, 0x7a, 0xe9, 0x59, 0x78,
	0xcd, 0x8d, 0x1d, 0xca, 0x8f, 0x83, 0x81, 0xc4, 0x30, 0x20, 0xcb, 0xb2, 0x2c, 0xd8, 0x31, 0x82,
	0xb6, 0xec, 0x83, 0x11, 0x60, 0x30, 0x9c, 0x29, 0x4a, 0x0d, 0x0e, 0xa7, 0x99, 0x9e, 0xa6, 0x5e,
	0xb7, 0x00, 0xb9, 0xe7, 0x96, 0x1f, 0x91, 0x9f, 0x93, 0x3f, 0x11, 0x20, 0xd7, 0xfc, 0x81, 0xa0,
	0x1f, 0x33, 0x1a, 0xbd, 0x05, 0xe5, 0x9a, 0xdb, 0x54, 0x55, 0x77, 0xd5, 0xd7, 0xf5, 0xf8, 0xba,
	0x31, 0xf0, 0x7c, 0x9b, 0xc9, 0x9d, 0xf9, 0x68, 0x18, 0xf2, 0xe9, 0x4a, 0xcc, 0xf9, 0x34, 0x41,
	0xb9, 0xc7, 0xc5, 0x64, 0xe5, 0x90, 0x4f, 0x47, 0x0c, 0xfd, 0x51, 0x20, 0x65, 0x8c, 0xdb, 0x82,
	0xcf, 0x93, 0x68, 0x45, 0x1e, 0xcc, 0x30, 0x5d, 0x39, 0x1c, 0xad, 0x1c, 0x8e, 0x86, 0x33, 0xc1,
	0x25, 0xf7, 0xfe, 0x28, 0x41, 0x7d, 0x35, 0x0c, 0xf9, 0x3c, 0x91, 0xe4, 0x16, 0xd4, 0xe7, 0x29,
	0x0a, 0x9f, 0x45, 0xae, 0xd3, 0x77, 0x06, 0x4d, 0x5a, 0x53, 0xe2, 0x66, 0x44, 0x9e, 0xc0, 0xcd,
	0xd9, 0x0e, 0x4f, 0xd0, 0x4f, 0xe6, 0xd3, 0x11, 0x0a, 0x7f, 0x17, 0x05, 0x1b, 0x33, 0x8c, 0xdc,
	0x52, 0xdf, 0x19, 0x34, 0xe8, 0x3f, 0xb4, 0xf1, 0xbd, 0xb6, 0x7d, 0xb2, 0x26, 0x72, 0x1f, 0xba,
	0x02, 0xf7, 0x02, 0x11, 0xf9, 0x02, 0x23, 0xc4, 0x29, 0x46, 0x6e, 0x59, 0xaf, 0xee, 0x18, 0x35,
	0xb5, 0x5a, 0x72, 0x0f, 0x3a, 0x2c, 0xf5, 0x27, 0x2c, 0x9c, 0xa4, 0x32, 0x10, 0x12, 0x85, 0x5b,
	0xd1, 0xeb, 0x16, 0x58, 0xfa, 0xf6, 0x48, 0x49, 0x16, 0xa1, 0xca, 0xa6, 0xc1, 0x36, 0xba, 0x55,
	0x0d, 0xcd, 0x08, 0xe4, 0x4b, 0x20, 0x38, 0x0d, 0x58, 0xec, 0x27, 0x5c, 0xb2, 0x31, 0x0b, 0x03,
	0xc9, 0x78, 0xe2, 0xd6, 0xb4, 0x83, 0x9e, 0xb6, 0xbc, 0x2f, 0x18, 0xc8, 0x32, 0x34, 0x31, 0xe6,
	0x7e, 0x1a, 0x72, 0x81, 0x6e, 0xbd, 0xef, 0x0c, 0xca, 0xb4, 0x81, 0x31, 0xff, 0xa0, 0x64, 0x72,
	0x17, 0xda, 0xe1, 0x5c, 0x08, 0x4c, 0xa4, 0x2f, 0x19, 0x0a, 0xb7, 0xd1, 0x77, 0x06, 0x55, 0xda,
	0xb2, 0xba, 0x2d, 0x86, 0x82, 0x3c, 0x82, 0xc5, 0xed, 0x60, 0x8a, 0xfe, 0x14, 0xd5, 0x59, 0xd3,
	0x1d, 0x36, 0x33, 0x4b, 0x9b, 0x7a, 0x29, 0x51, 0xb6, 0x6f, 0x72, 0x93, 0xde, 0xb1, 0x08, 0x55,
	0xbe, 0x97, 0xa0, 0x70, 0xa1, 0xef, 0x0c, 0xda, 0xd4, 0x08, 0xde, 0x67, 0xa8, 0xbc, 0xc2, 0x70,
	0x42, 0x08, 0x54, 0x92, 0x60, 0x8a, 0x36, 0xdd, 0xfa, 0x5b, 0x55, 0x61, 0x07, 0x05, 0x57, 0x55,
	0x28, 0x69, 0x84, 0x35, 0x25, 0x6e, 0xaa, 0x44, 0x55, 0xc3, 0x40, 0x44, 0xa9, 0x5b, 0xee, 0x97,
	0x07, 0xad, 0x27, 0xdd, 0xe1, 0x5a, 0x20, 0xa2, 0x35, 0x1e, 0xc7, 0x18, 0xaa, 0xc3, 0x51, 0x63,
	0xf5, 0x7e, 0x2d, 0x43, 0x45, 0x59, 0x48, 0x07, 0x4a, 0xb6, 0x92, 0x65, 0x5a, 0x62, 0x91, 0x0a,
	0x36, 0x61, 0x89, 0xf1, 0xda, 0xa4, 0xfa, 0x9b, 0xb8, 0x50, 0xc7, 0x18, 0xa7, 0x98, 0x48, 0x5d,
	0x9d, 0x26, 0xcd, 0xc4, 0x1c, 0x5a, 0xa5, 0x00, 0xad, 0x0f, 0xad, 0x08, 0xd3, 0x50, 0xb0, 0x99,
	0x4e, 0xb3, 0xa9, 0x44, 0x51, 0x45, 0xee, 0x00, 0x8c, 0xe3, 0x60, 0x97, 0x8b, 0x2d, 0xdc, 0x97,
	0xba, 0x0e, 0x4d, 0x5a, 0xd0, 0xa8, 0x78, 0x33, 0x16, 0xca, 0xb9, 0x4d, 0x7f, 0x93, 0x66, 0xa2,
	0x8a, 0x27, 0x82, 0x64, 0xa2, 0xb3, 0xde, 0xa4, 0xfa, 0x5b, 0xe9, 0x54, 0xc7, 0xea, 0xf4, 0x36,
	0xa9, 0xfe, 0x26, 0x4b, 0x50, 0x13, 0x81, 0x60, 0xf2, 0x40, 0x67, 0xb4, 0x49, 0xad, 0xa4, 0xf4,
	0x51, 0xa0, 0x1b, 0xa4, 0xa5, 0x8b, 0x61, 0x25, 0xa5, 0xdf, 0xc1, 0x20, 0x96, 0x3b, 0x6e, 0xdb,
	0xe8, 0x8d, 0xa4, 0x7c, 0x87, 0x3c, 0x95, 0xee, 0x82, 0xd6, 0xea, 0x6f, 0x85, 0x2e, 0x18, 0xb1,
	0x58, 0x39, 0xef, 0x18, 0x74, 0x56, 0x24, 0x4f, 0xa1, 0xa3, 0xb2, 0xeb, 0xef, 0x32, 0xdc, 0xf3,
	0x59, 0x32, 0xe6, 0x6e, 0xb7, 0xef, 0x0c, 0x5a, 0x4f, 0x16, 0x74, 0x11, 0x3e, 0x31, 0xdc, 0xdb,
	0x4c, 0xc6, 0x9c, 0xb6, 0xc3, 0x82, 0x44, 0xee, 0x42, 0x1d, 0xc7, 0x63, 0x0c, 0x65, 0xea, 0xde,
	0xd0, 0x25, 0xab, 0x0f, 0xd7, 0xb5, 0x4c, 0x33, 0x3d, 0xf9, 0x1f, 0x34, 0x4d, 0x08, 0x86, 0xa9,
	0xdb, 0xd3, 0x8b, 0x1a, 0xc3, 0x55, 0x13, 0x94, 0x1e, 0x99, 0xbc, 0xef, 0xa0, 0x5d, 0x0c, 0x44,
	0x06, 0xd0, 0x98, 0xf1, 0x94, 0xe9, 0x32, 0x38, 0x1a, 0x49, 0x7b, 0xb8, 0xc6, 0xb9, 0x88, 0x58,
	0x12, 0x48, 0x4c, 0x69, 0x6e, 0x25, 0x1e, 0x54, 0xd3, 0x30, 0x88, 0x51, 0x97, 0xfd, 0xe4, 0x32,
	0x63, 0xf2, 0x9e, 0x41, 0xab, 0xa0, 0x25, 0x6d, 0x70, 0xf6, 0xb5, 0xd7, 0x12, 0x75, 0xf6, 0x95,
	0x74, 0xa0, 0x37, 0x97, 0xa8, 0x73, 0xa0, 0xa4, 0x43, 0xdd, 0x2a, 0x25, 0xea, 0x1c, 0x7a, 0x3f,
	0x3a, 0x50, 0x33, 0x47, 0x52, 0xb9, 0x93, 0x82, 0x6d, 0x6f, 0xa3, 0xb0, 0xdd, 0x9c, 0x89, 0xaa,
	0x02, 0xe6, 0xb8, 0xb6, 0xf3, 0xac, 0x44, 0xfe, 0x05, 0x8d, 0x68, 0x2e, 0xcc, 0xc4, 0x9a, 0xe6,
	0xcb, 0x65, 0xb5, 0x47, 0x06, 0x62, 0x1b, 0xa5, 0xed, 0x3f, 0x2b, 0xa9, 0x71, 0x8a, 0xd9, 0x94,
	0xc9, 0x8c, 0x05, 0xb4, 0xe0, 0xfd, 0xec, 0x40, 0xdd, 0x26, 0x2d, 0xef, 0x19, 0xa7, 0xd0, 0x33,
	0xff, 0x85, 0x85, 0x20, 0x94, 0x6c, 0x97, 0xc9, 0x03, 0x5f, 0x1b, 0x0d, 0x90, 0x76, 0xa6, 0xdc,
	0x52, 0x8b, 0x96, 0xa1, 0x19, 0x06, 0x71, 0x6c, 0x16, 0x58, 0x3c, 0x4a, 0xa1, 0x8d, 0xff, 0x81,
	0x96, 0x41, 0x60, 0xcc, 0x06, 0x14, 0x18, 0x95, 0x5e, 0xb0, 0x08, 0xd5, 0xdd, 0x20, 0x9e, 0x1b,
	0x7a, 0xaa, 0x52, 0x23, 0x78, 0xf7, 0xa1, 0xa1, 0xca, 0xf6, 0x8e, 0xa5, 0x92, 0x2c, 0x67, 0xe3,
	0xeb, 0xe8, 0x32, 0x57, 0x75, 0xe7, 0x64, 0x43, 0xbb, 0x0e, 0x9d, 0xe3, 0xd3, 0x6c, 0xe0, 0x88,
	0xc8, 0x2f, 0xf0, 0x43, 0x43, 0x29, 0xde, 0xab, 0x41, 0x5c, 0x82, 0x5a, 0x30, 0x55, 0x9c, 0x9d,
	0x51, 0x84, 0x91, 0xbc, 0xaf, 0xa0, 0xae, 0xdc, 0x7c, 0x40, 0x79, 0x26, 0xb5, 0xe4, 0x10, 0x4a,
	0x67, 0x40, 0x78, 0x00, 0x2d, 0x83, 0x75, 0x24, 0x02, 0x71, 0x40, 0x6e, 0x43, 0x25, 0x45, 0x99,
	0xa1, 0x6d, 0x0c, 0xad, 0x5f, 0xaa, 0xb5, 0xde, 0x0f, 0x0e, 0x54, 0xde, 0xa0, 0xe0, 0x45, 0xb6,
	0x72, 0x8e, 0xb1, 0x15, 0x81, 0x0a, 0x0b, 0x79, 0x92, 0xb1, 0x8d, 0xfa, 0xce, 0x31, 0x95, 0x0b,
	0x98, 0x0a, 0x0c, 0x54, 0xd1, 0xa9, 0xcb, 0x19, 0xe8, 0x0e, 0xd4, 0xd2, 0x09, 0x8b, 0xe3, 0xd4,
	0xad, 0x6a, 0x0c, 0xb5, 0xe1, 0x07, 0x25, 0x52, 0xab, 0xf5, 0x26, 0xd0, 0x50, 0x10, 0xf4, 0x3c,
	0x9c, 0x0b, 0xe3, 0x0e, 0x00, 0xee, 0xcf, 0x50, 0x30, 0x4c, 0x42, 0xb4, 0xd9, 0x2a, 0x68, 0x8e,
	0x0f, 0x60, 0xf9, 0xfc, 0x01, 0x7c, 0x0c, 0xed, 0x2c, 0x98, 0xae, 0xe6, 0x5d, 0xd0, 0x11, 0x30,
	0x4b, 0x50, 0x73, 0x98, 0x99, 0xa9, 0x35, 0x78, 0x8f, 0x61, 0x69, 0x03, 0x65, 0x71, 0x17, 0xc5,
	0xef, 0xe7, 0x98, 0x9e, 0x7f, 0xd1, 0x7a, 0xcf, 0xe1, 0xd6, 0xa9, 0x2d, 0xe9, 0x8c, 0x27, 0x29,
	0x5e, 0x25, 0xe0, 0x0e, 0x2c, 0xae, 0x46, 0xd1, 0x7a, 0x7e, 0xb8, 0xcb, 0xc2, 0x9d, 0x7f, 0xd5,
	0x1c, 0xcf, 0x5a, 0xf9, 0x64, 0xd6, 0xbc, 0x6f, 0xe1, 0xe6, 0x89, 0x48, 0x16, 0xe5, 0x75, 0xeb,
	0xe0, 0xbd, 0x06, 0x52, 0x38, 0xf9, 0xb5, 0x91, 0x7b, 0x6f, 0xf3, 0x0c, 0xae, 0x66, 0xb5, 0xbb,
	0xbe, 0xb3, 0x97, 0xe0, 0x9e, 0x76, 0x66, 0x4f, 0x7a, 0xac, 0x71, 0x9c, 0xf3, 0x1b, 0xe7, 0x27,
	0x07, 0xaa, 0xba, 0x6f, 0x15, 0x45, 0x48, 0x26, 0xe3, 0x6c, 0x24, 0x8d, 0x40, 0x6e, 0x43, 0x53,
	0xf7, 0xf3, 0x56, 0xc6, 0x4b, 0x55, 0x7a, 0xa4, 0x20, 0x03, 0xe8, 0x1a, 0x21, 0x67, 0x1a, 0x5d,
	0x8d, 0x2a, 0x3d, 0xa9, 0xce, 0xef, 0xb3, 0x4a, 0xe1, 0x3e, 0x3b, 0x9b, 0x94, 0xfe, 0x6f, 0xe6,
	0x46, 0xb7, 0xf1, 0xbf, 0x4f, 0x74, 0x55, 0x55, 0x77, 0x55, 0xde, 0x51, 0x5f, 0x03, 0x39, 0x4e,
	0x4b, 0x7a, 0xd3, 0xbd, 0xe3, 0x4c, 0x76, 0xde, 0x43, 0xe4, 0x3e, 0x34, 0xd4, 0x23, 0x27, 0x23,
	0xbf, 0x08, 0xc3, 0xc9, 0x51, 0x18, 0x65, 0xa1, 0x46, 0xe7, 0xfd, 0xe6, 0x40, 0x6b, 0x33, 0x61,
	0xf9, 0x78, 0x7c, 0x01, 0x0b, 0x11, 0x8e, 0x83, 0x79, 0x2c, 0xfd, 0x33, 0x36, 0xb5, 0xad, 0x4d,
	0x09, 0x29, 0x79, 0x01, 0x24, 0x5b, 0x1b, 0xe6, 0x08, 0x2c, 0xbf, 0x9d, 0x02, 0xd6, 0xb3, 0x4b,
	0x0b, 0x34, 0xfb, 0x08, 0x3a, 0xd9, 0x7e, 0x9b, 0x88, 0xf2, 0xc9, 0xf1, 0xca, 0xc0, 0xbc, 0xd1,
	0xf6, 0x23, 0x12, 0xad, 0x9c, 0x26, 0xd1, 0x42, 0x3e, 0xab, 0x67, 0xe5, 0xf3, 0xf7, 0x12, 0x2c,
	0x7e, 0x9c, 0xa5, 0x28, 0xa4, 0x7d, 0x73, 0x5f, 0xda, 0x9b, 0x7f, 0x3f, 0xbd, 0xaf, 0xfb, 0xf4,
	0xf6, 0x1e, 0x42, 0x6f, 0x03, 0xaf, 0x9a, 0x68, 0xef, 0x35, 0x74, 0x36, 0x50, 0x37, 0xd5, 0xa5,
	0x35, 0x59, 0x86, 0xa6, 0xea, 0x4b, 0x73, 0x35, 0x97, 0xec, 0xcb, 0x05, 0xc3, 0x89, 0xba, 0x9a,
	0xbd, 0x87, 0xd0, 0xcd, 0xfd, 0x58, 0xaa, 0xf8, 0x27, 0x54, 0x94, 0xd9, 0xbe, 0xc0, 0x6c, 0x1b,
	0x6b, 0x95, 0xb7, 0x01, 0xbd, 0x35, 0x81, 0x81, 0xc4, 0x2b, 0x05, 0xbe, 0xc0, 0xd1, 0x26, 0xf4,
	0x5e, 0x61, 0x8c, 0x57, 0x74, 0x74, 0xe1, 0x09, 0xd6, 0xa1, 0xbb, 0x1e, 0x31, 0xf9, 0x57, 0x11,
	0xad, 0xc3, 0x82, 0x1e, 0xd1, 0xe2, 0xdd, 0x70, 0x1e, 0x1a, 0x4b, 0x0e, 0xa5, 0x33, 0xc8, 0xe1,
	0x01, 0xdc, 0x50, 0x0c, 0x62, 0x5d, 0x5d, 0x52, 0xc4, 0x47, 0xd0, 0x2b, 0x2c, 0xb6, 0x71, 0x2f,
	0xe4, 0x1e, 0x17, 0x96, 0xd4, 0x8e, 0xc2, 0xcb, 0xc7, 0x06, 0xf1, 0x9e, 0xc1, 0xad, 0x53, 0x16,
	0xeb, 0xf1, 0xe2, 0xb7, 0x51, 0x0f, 0xba, 0x6a, 0xa3, 0x1e, 0x7c, 0xeb, 0xeb, 0xb1, 0x39, 0x84,
	0x51, 0x59, 0x27, 0x97, 0x50, 0xef, 0x0a, 0x2c, 0x6e, 0x60, 0x81, 0xa9, 0x2e, 0x3d, 0xfb, 0x0b,
	0xb8, 0x79, 0x62, 0x83, 0x0d, 0x74, 0x35, 0xba, 0x7e, 0x49, 0x7e, 0x29, 0x75, 0xdf, 0x71, 0x3e,
	0x1d, 0x7e, 0x4c, 0x98, 0x3c, 0x78, 0x1a, 0x0d, 0x3f, 0x8f, 0x46, 0x35, 0xfd, 0x93, 0xe0, 0xe9,
	0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x41, 0x4c, 0xab, 0x11, 0x64, 0x10, 0x00, 0x00,
}
