// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/loomnetwork/zombie_battleground/types/zb/zb.proto

/*
Package zb is a generated protocol buffer package.

It is generated from these files:
	github.com/loomnetwork/zombie_battleground/types/zb/zb.proto

It has these top-level messages:
	Account
	UpsertAccountRequest
	GetAccountRequest
*/
package zb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import types "github.com/loomnetwork/go-loom/types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Account struct {
	UserId              string         `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PhoneNumberVerified bool           `protobuf:"varint,2,opt,name=phone_number_verified,json=phoneNumberVerified,proto3" json:"phone_number_verified,omitempty"`
	RewardRedeemed      bool           `protobuf:"varint,3,opt,name=reward_redeemed,json=rewardRedeemed,proto3" json:"reward_redeemed,omitempty"`
	IsKickstarter       bool           `protobuf:"varint,4,opt,name=is_kickstarter,json=isKickstarter,proto3" json:"is_kickstarter,omitempty"`
	Image               string         `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	EmailNotification   bool           `protobuf:"varint,6,opt,name=email_notification,json=emailNotification,proto3" json:"email_notification,omitempty"`
	EloScore            int64          `protobuf:"varint,7,opt,name=elo_score,json=eloScore,proto3" json:"elo_score,omitempty"`
	CurrentTier         int32          `protobuf:"varint,8,opt,name=current_tier,json=currentTier,proto3" json:"current_tier,omitempty"`
	GameMembershipTier  int32          `protobuf:"varint,9,opt,name=game_membership_tier,json=gameMembershipTier,proto3" json:"game_membership_tier,omitempty"`
	Owner               *types.Address `protobuf:"bytes,10,opt,name=owner" json:"owner,omitempty"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{0} }

func (m *Account) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Account) GetPhoneNumberVerified() bool {
	if m != nil {
		return m.PhoneNumberVerified
	}
	return false
}

func (m *Account) GetRewardRedeemed() bool {
	if m != nil {
		return m.RewardRedeemed
	}
	return false
}

func (m *Account) GetIsKickstarter() bool {
	if m != nil {
		return m.IsKickstarter
	}
	return false
}

func (m *Account) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *Account) GetEmailNotification() bool {
	if m != nil {
		return m.EmailNotification
	}
	return false
}

func (m *Account) GetEloScore() int64 {
	if m != nil {
		return m.EloScore
	}
	return 0
}

func (m *Account) GetCurrentTier() int32 {
	if m != nil {
		return m.CurrentTier
	}
	return 0
}

func (m *Account) GetGameMembershipTier() int32 {
	if m != nil {
		return m.GameMembershipTier
	}
	return 0
}

func (m *Account) GetOwner() *types.Address {
	if m != nil {
		return m.Owner
	}
	return nil
}

type UpsertAccountRequest struct {
	UserId              string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PhoneNumberVerified bool   `protobuf:"varint,2,opt,name=phone_number_verified,json=phoneNumberVerified,proto3" json:"phone_number_verified,omitempty"`
	RewardRedeemed      bool   `protobuf:"varint,3,opt,name=reward_redeemed,json=rewardRedeemed,proto3" json:"reward_redeemed,omitempty"`
	IsKickstarter       bool   `protobuf:"varint,4,opt,name=is_kickstarter,json=isKickstarter,proto3" json:"is_kickstarter,omitempty"`
	Image               string `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	EmailNotification   bool   `protobuf:"varint,6,opt,name=email_notification,json=emailNotification,proto3" json:"email_notification,omitempty"`
	EloScore            int64  `protobuf:"varint,7,opt,name=elo_score,json=eloScore,proto3" json:"elo_score,omitempty"`
	CurrentTier         int32  `protobuf:"varint,8,opt,name=current_tier,json=currentTier,proto3" json:"current_tier,omitempty"`
	GameMembershipTier  int32  `protobuf:"varint,9,opt,name=game_membership_tier,json=gameMembershipTier,proto3" json:"game_membership_tier,omitempty"`
}

func (m *UpsertAccountRequest) Reset()                    { *m = UpsertAccountRequest{} }
func (m *UpsertAccountRequest) String() string            { return proto.CompactTextString(m) }
func (*UpsertAccountRequest) ProtoMessage()               {}
func (*UpsertAccountRequest) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{1} }

func (m *UpsertAccountRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpsertAccountRequest) GetPhoneNumberVerified() bool {
	if m != nil {
		return m.PhoneNumberVerified
	}
	return false
}

func (m *UpsertAccountRequest) GetRewardRedeemed() bool {
	if m != nil {
		return m.RewardRedeemed
	}
	return false
}

func (m *UpsertAccountRequest) GetIsKickstarter() bool {
	if m != nil {
		return m.IsKickstarter
	}
	return false
}

func (m *UpsertAccountRequest) GetImage() string {
	if m != nil {
		return m.Image
	}
	return ""
}

func (m *UpsertAccountRequest) GetEmailNotification() bool {
	if m != nil {
		return m.EmailNotification
	}
	return false
}

func (m *UpsertAccountRequest) GetEloScore() int64 {
	if m != nil {
		return m.EloScore
	}
	return 0
}

func (m *UpsertAccountRequest) GetCurrentTier() int32 {
	if m != nil {
		return m.CurrentTier
	}
	return 0
}

func (m *UpsertAccountRequest) GetGameMembershipTier() int32 {
	if m != nil {
		return m.GameMembershipTier
	}
	return 0
}

type GetAccountRequest struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (m *GetAccountRequest) Reset()                    { *m = GetAccountRequest{} }
func (m *GetAccountRequest) String() string            { return proto.CompactTextString(m) }
func (*GetAccountRequest) ProtoMessage()               {}
func (*GetAccountRequest) Descriptor() ([]byte, []int) { return fileDescriptorZb, []int{2} }

func (m *GetAccountRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func init() {
	proto.RegisterType((*Account)(nil), "Account")
	proto.RegisterType((*UpsertAccountRequest)(nil), "UpsertAccountRequest")
	proto.RegisterType((*GetAccountRequest)(nil), "GetAccountRequest")
}

func init() {
	proto.RegisterFile("github.com/loomnetwork/zombie_battleground/types/zb/zb.proto", fileDescriptorZb)
}

var fileDescriptorZb = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x93, 0x4f, 0x8b, 0xd4, 0x30,
	0x18, 0xc6, 0xe9, 0xac, 0x9d, 0xe9, 0x64, 0x75, 0x65, 0xe3, 0x88, 0x41, 0x41, 0xea, 0x80, 0xd8,
	0x83, 0x3b, 0x5d, 0xd6, 0xab, 0x97, 0x3d, 0x89, 0x88, 0x7b, 0xa8, 0x7f, 0xae, 0xa1, 0x6d, 0xde,
	0xe9, 0x84, 0x69, 0xf2, 0xd6, 0x37, 0xa9, 0x83, 0xf3, 0x91, 0xfd, 0x0e, 0x82, 0x34, 0x2d, 0xea,
	0x45, 0xf0, 0xe2, 0x6d, 0x2f, 0x81, 0xe7, 0xf9, 0x3d, 0x4f, 0x48, 0xf2, 0x12, 0xf6, 0xba, 0xd1,
	0x7e, 0xd7, 0x57, 0x9b, 0x1a, 0x4d, 0xde, 0x22, 0x1a, 0x0b, 0xfe, 0x80, 0xb4, 0xcf, 0x8f, 0x68,
	0x2a, 0x0d, 0xb2, 0x2a, 0xbd, 0x6f, 0xa1, 0x21, 0xec, 0xad, 0xca, 0xfd, 0xb7, 0x0e, 0x5c, 0x7e,
	0xac, 0xf2, 0x63, 0xb5, 0xe9, 0x08, 0x3d, 0x3e, 0xbe, 0xfc, 0x4b, 0xbb, 0xc1, 0x8b, 0x41, 0x4e,
	0x8d, 0xb0, 0x8e, 0x8d, 0xf5, 0x8f, 0x19, 0x5b, 0x5c, 0xd7, 0x35, 0xf6, 0xd6, 0xf3, 0x47, 0x6c,
	0xd1, 0x3b, 0x20, 0xa9, 0x95, 0x88, 0xd2, 0x28, 0x5b, 0x16, 0xf3, 0x41, 0xbe, 0x55, 0xfc, 0x8a,
	0x3d, 0xec, 0x76, 0x68, 0x41, 0xda, 0xde, 0x54, 0x40, 0xf2, 0x2b, 0x90, 0xde, 0x6a, 0x50, 0x62,
	0x96, 0x46, 0x59, 0x52, 0x3c, 0x08, 0xf0, 0x26, 0xb0, 0xcf, 0x13, 0xe2, 0x2f, 0xd8, 0x7d, 0x82,
	0x43, 0x49, 0x4a, 0x12, 0x28, 0x00, 0x03, 0x4a, 0x9c, 0x84, 0xf4, 0xd9, 0x68, 0x17, 0x93, 0xcb,
	0x9f, 0xb3, 0x33, 0xed, 0xe4, 0x5e, 0xd7, 0x7b, 0xe7, 0x4b, 0xf2, 0x40, 0xe2, 0x4e, 0xc8, 0xdd,
	0xd3, 0xee, 0xdd, 0x6f, 0x93, 0xaf, 0x58, 0xac, 0x4d, 0xd9, 0x80, 0x88, 0xc3, 0xd1, 0x46, 0xc1,
	0x2f, 0x18, 0x07, 0x53, 0xea, 0x56, 0x5a, 0xf4, 0x7a, 0xab, 0xeb, 0xd2, 0x6b, 0xb4, 0x62, 0x1e,
	0x36, 0x38, 0x0f, 0xe4, 0xe6, 0x0f, 0xc0, 0x9f, 0xb0, 0x25, 0xb4, 0x28, 0x5d, 0x8d, 0x04, 0x62,
	0x91, 0x46, 0xd9, 0x49, 0x91, 0x40, 0x8b, 0x1f, 0x06, 0xcd, 0x9f, 0xb1, 0xbb, 0x75, 0x4f, 0x04,
	0xd6, 0x4b, 0xaf, 0x81, 0x44, 0x92, 0x46, 0x59, 0x5c, 0x9c, 0x4e, 0xde, 0x47, 0x0d, 0xc4, 0x2f,
	0xd9, 0xaa, 0x29, 0x0d, 0x48, 0x03, 0xc3, 0x5d, 0xdd, 0x4e, 0x77, 0x63, 0x74, 0x19, 0xa2, 0x7c,
	0x60, 0xef, 0x7f, 0xa1, 0xd0, 0x78, 0xca, 0x62, 0x3c, 0x58, 0x20, 0xc1, 0xd2, 0x28, 0x3b, 0xbd,
	0x4a, 0x36, 0xd7, 0x4a, 0x11, 0x38, 0x57, 0x8c, 0xf6, 0xfa, 0xfb, 0x8c, 0xad, 0x3e, 0x75, 0x0e,
	0xc8, 0x4f, 0x53, 0x28, 0xe0, 0x4b, 0x0f, 0xee, 0x76, 0x18, 0xff, 0x61, 0x18, 0xeb, 0x97, 0xec,
	0xfc, 0x0d, 0xfc, 0xeb, 0x43, 0x57, 0xf3, 0xf0, 0x43, 0x5e, 0xfd, 0x0c, 0x00, 0x00, 0xff, 0xff,
	0xe1, 0x71, 0x09, 0x98, 0x93, 0x03, 0x00, 0x00,
}
