// Generated by pbgraphserialization-gen. DO NOT EDIT.
// targetPackagePath: github.com/loomnetwork/gamechain/battleground/game/
// targetPackageName: game
// protoPackageName: zb

package game

import pbgraphserialization "github.com/loomnetwork/gamechain/library/pbgraphserialization"
import pbgraphserialization_pb "github.com/loomnetwork/gamechain/library/pbgraphserialization/proto/pbgraphserialization"
import proto "github.com/gogo/protobuf/proto"
import zb "github.com/loomnetwork/gamechain/types/zb"

func (deckCard *DeckCard) Serialize(serializer *pbgraphserialization.Serializer) proto.Message {
	serialized := &zb.DeckCard{}
	serialized.CardName = string(deckCard.cardName)
	serialized.Amount = int64(deckCard.amount)
	return serialized
}

func (deckCard *DeckCard) Deserialize(deserializer *pbgraphserialization.Deserializer, rawMessage proto.Message) (pbgraphserialization.SerializableObject, error) {
	serialized := rawMessage.(*zb.DeckCard)
	deckCard.cardName = string(serialized.CardName)
	deckCard.amount = int64(serialized.Amount)
	return deckCard, nil
}

func (deck *Deck) Serialize(serializer *pbgraphserialization.Serializer) proto.Message {
	serialized := &zb.Deck{}
	serialized.Name = string(deck.name)
	serialized.Id = int64(deck.id)
	serialized.HeroId = int64(deck.heroId)
	serialized.SecondarySkill = zb.OverlordSkillKind_Enum(deck.secondarySkill)
	serialized.PrimarySkill = zb.OverlordSkillKind_Enum(deck.primarySkill)

	for _, deckcardsElement := range deck.cards {
		var deckcardsElementSerialized *zb.DeckCard
		deckcardsElementSerialized = serializer.Serialize(deckcardsElement).Serialize()
		serialized.Cards = append(serialized.Cards, deckcardsElementSerialized)
	}

	return serialized
}

func (deck *Deck) Deserialize(deserializer *pbgraphserialization.Deserializer, rawMessage proto.Message) (pbgraphserialization.SerializableObject, error) {
	serialized := rawMessage.(*zb.Deck)
	deck.name = string(serialized.Name)
	deck.id = int64(serialized.Id)
	deck.heroId = int64(serialized.HeroId)
	deck.secondarySkill = OverlordSkillKind_Enum(serialized.SecondarySkill)
	deck.primarySkill = OverlordSkillKind_Enum(serialized.PrimarySkill)

	for _, serializedCardsElement := range serialized.Cards {
		var serializedCardsElementDeserialized *DeckCard
		serializedCardsElementDeserializedDeserialized, err := deserializer.Deserialize(
			serializedCardsElement,
			func() pbgraphserialization.SerializableObject { return &DeckCard{} },
			func() proto.Message { return &zb.DeckCard{} },
		)

		if err != nil {
			return nil, err
		}

		serializedCardsElementDeserialized = serializedCardsElementDeserializedDeserialized.(*DeckCard)
		deck.cards = append(deck.cards, serializedCardsElementDeserialized)
	}

	return deck, nil
}
