// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/loomnetwork/zombie_battleground/types/zbcard/zbcard.proto

/*
Package zbcard is a generated protocol buffer package.

It is generated from these files:
	github.com/loomnetwork/zombie_battleground/types/zbcard/zbcard.proto

It has these top-level messages:
	Card
	Effect
	CardList
	InitRequest
*/
package zbcard

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Card struct {
	Id      string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Element string    `protobuf:"bytes,3,opt,name=element,proto3" json:"element,omitempty"`
	Rank    string    `protobuf:"bytes,4,opt,name=rank,proto3" json:"rank,omitempty"`
	Type    string    `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Attack  int32     `protobuf:"varint,6,opt,name=attack,proto3" json:"attack,omitempty"`
	Defence int32     `protobuf:"varint,7,opt,name=defence,proto3" json:"defence,omitempty"`
	GooCost int32     `protobuf:"varint,8,opt,name=goo_cost,json=gooCost,proto3" json:"goo_cost,omitempty"`
	Ability string    `protobuf:"bytes,9,opt,name=ability,proto3" json:"ability,omitempty"`
	Effects []*Effect `protobuf:"bytes,10,rep,name=effects" json:"effects,omitempty"`
}

func (m *Card) Reset()                    { *m = Card{} }
func (m *Card) String() string            { return proto.CompactTextString(m) }
func (*Card) ProtoMessage()               {}
func (*Card) Descriptor() ([]byte, []int) { return fileDescriptorZbcard, []int{0} }

func (m *Card) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Card) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Card) GetElement() string {
	if m != nil {
		return m.Element
	}
	return ""
}

func (m *Card) GetRank() string {
	if m != nil {
		return m.Rank
	}
	return ""
}

func (m *Card) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Card) GetAttack() int32 {
	if m != nil {
		return m.Attack
	}
	return 0
}

func (m *Card) GetDefence() int32 {
	if m != nil {
		return m.Defence
	}
	return 0
}

func (m *Card) GetGooCost() int32 {
	if m != nil {
		return m.GooCost
	}
	return 0
}

func (m *Card) GetAbility() string {
	if m != nil {
		return m.Ability
	}
	return ""
}

func (m *Card) GetEffects() []*Effect {
	if m != nil {
		return m.Effects
	}
	return nil
}

type Effect struct {
	Trigger  string `protobuf:"bytes,1,opt,name=trigger,proto3" json:"trigger,omitempty"`
	Effect   string `protobuf:"bytes,2,opt,name=effect,proto3" json:"effect,omitempty"`
	Duration string `protobuf:"bytes,3,opt,name=duration,proto3" json:"duration,omitempty"`
	Target   string `protobuf:"bytes,4,opt,name=target,proto3" json:"target,omitempty"`
	Limit    string `protobuf:"bytes,5,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (m *Effect) Reset()                    { *m = Effect{} }
func (m *Effect) String() string            { return proto.CompactTextString(m) }
func (*Effect) ProtoMessage()               {}
func (*Effect) Descriptor() ([]byte, []int) { return fileDescriptorZbcard, []int{1} }

func (m *Effect) GetTrigger() string {
	if m != nil {
		return m.Trigger
	}
	return ""
}

func (m *Effect) GetEffect() string {
	if m != nil {
		return m.Effect
	}
	return ""
}

func (m *Effect) GetDuration() string {
	if m != nil {
		return m.Duration
	}
	return ""
}

func (m *Effect) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *Effect) GetLimit() string {
	if m != nil {
		return m.Limit
	}
	return ""
}

type CardList struct {
	Cards []*Card `protobuf:"bytes,1,rep,name=cards" json:"cards,omitempty"`
}

func (m *CardList) Reset()                    { *m = CardList{} }
func (m *CardList) String() string            { return proto.CompactTextString(m) }
func (*CardList) ProtoMessage()               {}
func (*CardList) Descriptor() ([]byte, []int) { return fileDescriptorZbcard, []int{2} }

func (m *CardList) GetCards() []*Card {
	if m != nil {
		return m.Cards
	}
	return nil
}

type InitRequest struct {
	Cardlist *CardList `protobuf:"bytes,1,opt,name=cardlist" json:"cardlist,omitempty"`
}

func (m *InitRequest) Reset()                    { *m = InitRequest{} }
func (m *InitRequest) String() string            { return proto.CompactTextString(m) }
func (*InitRequest) ProtoMessage()               {}
func (*InitRequest) Descriptor() ([]byte, []int) { return fileDescriptorZbcard, []int{3} }

func (m *InitRequest) GetCardlist() *CardList {
	if m != nil {
		return m.Cardlist
	}
	return nil
}

func init() {
	proto.RegisterType((*Card)(nil), "Card")
	proto.RegisterType((*Effect)(nil), "Effect")
	proto.RegisterType((*CardList)(nil), "CardList")
	proto.RegisterType((*InitRequest)(nil), "InitRequest")
}

func init() {
	proto.RegisterFile("github.com/loomnetwork/zombie_battleground/types/zbcard/zbcard.proto", fileDescriptorZbcard)
}

var fileDescriptorZbcard = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x91, 0xcd, 0xae, 0xd3, 0x30,
	0x10, 0x85, 0x95, 0xb6, 0xf9, 0xe9, 0x54, 0x62, 0x61, 0x21, 0x64, 0x60, 0x53, 0x22, 0x21, 0xba,
	0x4a, 0xa4, 0xc2, 0x1b, 0x14, 0x16, 0x48, 0xac, 0xf2, 0x02, 0x95, 0x93, 0x4c, 0x83, 0xd5, 0xc4,
	0x2e, 0xf6, 0x44, 0xa8, 0x5d, 0xdf, 0x67, 0xbe, 0xeb, 0x2b, 0xff, 0xa4, 0xab, 0xcc, 0x77, 0x66,
	0x3c, 0x39, 0x3e, 0x86, 0x9f, 0x83, 0xa4, 0xbf, 0x73, 0x5b, 0x75, 0x7a, 0xaa, 0x47, 0xad, 0x27,
	0x85, 0xf4, 0x5f, 0x9b, 0x6b, 0xfd, 0xd0, 0x53, 0x2b, 0xf1, 0xdc, 0x0a, 0xa2, 0x11, 0x07, 0xa3,
	0x67, 0xd5, 0xd7, 0x74, 0xbf, 0xa1, 0xad, 0x1f, 0x6d, 0x27, 0x4c, 0x1f, 0x3f, 0xd5, 0xcd, 0x68,
	0xd2, 0xe5, 0x6b, 0x02, 0x9b, 0x93, 0x30, 0x3d, 0x7b, 0x07, 0x2b, 0xd9, 0xf3, 0x64, 0x9f, 0x1c,
	0xb6, 0xcd, 0x4a, 0xf6, 0x8c, 0xc1, 0x46, 0x89, 0x09, 0xf9, 0xca, 0x2b, 0xbe, 0x66, 0x1c, 0x72,
	0x1c, 0x71, 0x42, 0x45, 0x7c, 0xed, 0xe5, 0x05, 0xdd, 0xb4, 0x11, 0xea, 0xca, 0x37, 0x61, 0xda,
	0xd5, 0x4e, 0x73, 0xff, 0xe5, 0x69, 0xd0, 0x5c, 0xcd, 0x3e, 0x40, 0x26, 0x88, 0x44, 0x77, 0xe5,
	0xd9, 0x3e, 0x39, 0xa4, 0x4d, 0x24, 0xb7, 0xb9, 0xc7, 0x0b, 0xaa, 0x0e, 0x79, 0xee, 0x1b, 0x0b,
	0xb2, 0x8f, 0x50, 0x0c, 0x5a, 0x9f, 0x3b, 0x6d, 0x89, 0x17, 0xa1, 0x35, 0x68, 0x7d, 0xd2, 0x96,
	0xdc, 0x21, 0xd1, 0xca, 0x51, 0xd2, 0x9d, 0x6f, 0x83, 0x9d, 0x88, 0xec, 0x0b, 0xe4, 0x78, 0xb9,
	0x60, 0x47, 0x96, 0xc3, 0x7e, 0x7d, 0xd8, 0x1d, 0xf3, 0xea, 0x97, 0xe7, 0x66, 0xd1, 0xcb, 0x97,
	0x04, 0xb2, 0xa0, 0xb9, 0x3d, 0x64, 0xe4, 0x30, 0xa0, 0x89, 0xf7, 0x5f, 0xd0, 0xd9, 0x0d, 0xf3,
	0x31, 0x86, 0x48, 0xec, 0x13, 0x14, 0xfd, 0x6c, 0x04, 0x49, 0xad, 0x62, 0x12, 0x4f, 0x76, 0x67,
	0x48, 0x98, 0x01, 0x29, 0x86, 0x11, 0x89, 0xbd, 0x87, 0x74, 0x94, 0x93, 0xa4, 0x98, 0x47, 0x80,
	0xf2, 0x1b, 0x14, 0x2e, 0xfe, 0x3f, 0xd2, 0x12, 0xfb, 0x0c, 0xa9, 0x7b, 0x19, 0xcb, 0x13, 0xef,
	0x39, 0xad, 0x5c, 0xa7, 0x09, 0x5a, 0xf9, 0x03, 0x76, 0xbf, 0x95, 0xa4, 0x06, 0xff, 0xcd, 0x68,
	0x89, 0x7d, 0x85, 0xc2, 0xe9, 0xa3, 0xb4, 0xe4, 0x4d, 0xef, 0x8e, 0xdb, 0x6a, 0x59, 0xd4, 0x3c,
	0x5b, 0x6d, 0xe6, 0x5f, 0xf9, 0xfb, 0x5b, 0x00, 0x00, 0x00, 0xff, 0xff, 0x76, 0xf9, 0x39, 0xde,
	0x2d, 0x02, 0x00, 0x00,
}
